// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bguymwpnktdylzaediul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJndXltd3Bua3RkeWx6YWVkaXVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY5NTc4MzgsImV4cCI6MjA1MjUzMzgzOH0.dNoPPuzIly3mby15ek1XutZpbw7y2maRvu0mT7fXOaA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);